image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - docker info

stages:        
  - build
  - test

build-job:
  stage: build
  only:
    - master
  script:
    - echo "Building app with maven, result is jar"
    - apk --no-cache add openjdk17 maven
    - mvn package
    - mkdir artifacts_jars
    - mv target/*.jar artifacts_jars/userService.jar

  artifacts:
    expire_in: 2 hrs
    paths:
      - artifacts_jars


unit-test-job:
  stage: test
  only:
    - master
  script:
    - echo "Run tests"
    - apk --no-cache add openjdk17 maven
    - mvn test