image: docker:20.10.16

# to run docker in docker(dind), another image
services:
  - name: docker:20.10.16-dind
    alias: docker

stages:        
  - build
  - test
  - build-docker-image

build-job:
  stage: build
  only:
    - master
  script:
    - echo "Building app with maven, result is jar"
    - apk --no-cache add openjdk17 maven
    - mvn package
    - mkdir artifacts_jars
    - mv target/*.jar artifacts_jars/userService.jar

  artifacts:
    expire_in: 2 hrs
    paths:
      - artifacts_jars


unit-test-job:
  stage: test
  only:
    - master
  script:
    - echo "Run tests"
    - apk --no-cache add openjdk17 maven
    - mvn test

build-docker-image-job:
  stage: build-docker-image
  only:
    - master
  script:
    - docker info
    - docker exec ls

  artifacts:
    expire_in: 2 hrs
    paths:
      - /var/lib/docker/