image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - integration-tests

run-integration-tests-job:
  stage: integration-tests
  only:
    - master
  script:
    - echo "Runnig integration tests"
    - apk --no-cache add openjdk17 maven
    - docker-compose up --build -d
    - echo "Waiting until containers fully run"
    - sleep 1m
    - cd integration-tests
    - mvn test
