version: '2.3'

services:
  user-service:
    container_name: "user-service"
    image: "matthewgdocker/swa-user-service:latest"
    depends_on:
      - user-service-db
      - service-discovery
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_URI=http://service-discovery:8761/eureka/
    ports:
      - "8234:8234"
    healthcheck:
      test: "curl localhost:8234/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 45s
  use-service-db:
    container_name: "user-service-db"
    image: "postgres:16.3-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=USER_DB
  
  reservation-service:
    container_name: "reservation-service"
    image: "matthewgdocker/swa-reservation-service:latest"
    depends_on:
      - reservation-service-db
      - service-discovery
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_URI=http://service-discovery:8761/eureka/
    ports:
      - "8235:8235"
    healthcheck:
      test: "curl localhost:8235/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 45s
  reservation-service-db:
    container_name: "reservation-service-db"
    image: "postgres:16.3-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=RESERVATION_DB

  mail-service:
    container_name: "mail-service"
    image: "matthewgdocker/swa-mail-service:latest"
    depends_on:
      - service-discovery
    environment:
      - EUREKA_URI=http://service-discovery:8761/eureka/
    ports:
      - "8236:8236"
    healthcheck:
      test: "curl localhost:8236/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 45s

  service-discovery:
    container_name: "service-discovery"
    image: "matthewgdocker/swa-service-discovery:latest"
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl localhost:8761/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 45s
